
#pragma once

#define CONFIG_ARM_HIKEY_OUTSTANDING_PREFETCHERS  0
#define CONFIG_ARM_HIKEY_PREFETCHER_STRIDE  0
#define CONFIG_ARM_HIKEY_PREFETCHER_NPFSTRM  0
/* disabled: CONFIG_ARM_HIKEY_PREFETCHER_STBPFDIS */
/* disabled: CONFIG_ARM_HIKEY_PREFETCHER_STBPFRS */
/* disabled: CONFIG_PLAT_IMX7 */
/* disabled: CONFIG_ARCH_AARCH32 */
/* disabled: CONFIG_ARCH_AARCH64 */
/* disabled: CONFIG_ARCH_ARM_HYP */
/* disabled: CONFIG_ARCH_RISCV32 */
/* disabled: CONFIG_ARCH_RISCV64 */
#define CONFIG_ARCH_X86_64  1  /* KernelSel4ArchX86_64=ON */
/* disabled: CONFIG_ARCH_IA32 */
#define CONFIG_SEL4_ARCH  x86_64
#define CONFIG_ARCH_X86  1  /* KernelArchX86=ON */
#define CONFIG_ARCH  x86
#define CONFIG_WORD_SIZE  64
#define CONFIG_PC99_TSC_FREQUENCY  0
#define CONFIG_USER_TOP  0xa0000000
#define CONFIG_PLAT_PC99  1  /* KernelPlatPC99=ON */
#define CONFIG_PLAT_PC99  1  /* KernelPlatPC99=ON */
#define CONFIG_PLAT  pc99
/* disabled: CONFIG_ARM_CORTEX_A7 */
/* disabled: CONFIG_ARM_CORTEX_A8 */
/* disabled: CONFIG_ARM_CORTEX_A9 */
/* disabled: CONFIG_ARM_CORTEX_A15 */
/* disabled: CONFIG_ARM_CORTEX_A35 */
/* disabled: CONFIG_ARM_CORTEX_A53 */
/* disabled: CONFIG_ARM_CORTEX_A55 */
/* disabled: CONFIG_ARM_CORTEX_A57 */
/* disabled: CONFIG_ARM_CORTEX_A72 */
/* disabled: CONFIG_ARCH_ARM_V7A */
/* disabled: CONFIG_ARCH_ARM_V7VE */
/* disabled: CONFIG_ARCH_ARM_V8A */
/* disabled: CONFIG_ARM_SMMU */
/* disabled: CONFIG_AARCH64_SERROR_IGNORE */
/* disabled: CONFIG_KERNEL_MCS */
/* disabled: CONFIG_ARCH_X86_NEHALEM */
/* disabled: CONFIG_ARCH_X86_GENERIC */
/* disabled: CONFIG_ARCH_X86_WESTMERE */
/* disabled: CONFIG_ARCH_X86_SANDY */
/* disabled: CONFIG_ARCH_X86_IVY */
/* disabled: CONFIG_ARCH_X86_HASWELL */
/* disabled: CONFIG_ARCH_X86_BROADWELL */
/* disabled: CONFIG_ARCH_X86_SKYLAKE */
#define CONFIG_KERNEL_X86_MICRO_ARCH  nehalem
#define CONFIG_ARCH_X86_NEHALEM  1  /* KernelX86MicroArchNehalem=ON */
/* disabled: CONFIG_IRQ_IOAPIC */
/* disabled: CONFIG_IRQ_PIC */
#define CONFIG_KERNEL_IRQ_CONTROLLER  IOAPIC
#define CONFIG_IRQ_IOAPIC  1  /* KernelIRQControllerIOAPIC=ON */
#define CONFIG_MAX_NUM_IOAPIC  1
/* disabled: CONFIG_XAPIC */
/* disabled: CONFIG_X2APIC */
#define CONFIG_KERNEL_LAPIC_MODE  XAPIC
#define CONFIG_XAPIC  1  /* KernelLAPICModeXPAIC=ON */
/* disabled: CONFIG_USE_LOGCAL_IDS */
#define CONFIG_CACHE_LN_SZ  64
/* disabled: CONFIG_VTX */
/* disabled: CONFIG_IOMMU */
#define CONFIG_MAX_RMRR_ENTRIES  1
#define CONFIG_MAX_VPIDS  0
#define CONFIG_HUGE_PAGE  1  /* KernelHugePage=ON */
/* disabled: CONFIG_SUPPORT_PCID */
/* disabled: CONFIG_SYSCALL */
/* disabled: CONFIG_SYSENTER */
#define CONFIG_KERNEL_X86_SYSCALL  syscall
#define CONFIG_SYSCALL  1  /* KernelX86SyscallSyscall=ON */
/* disabled: CONFIG_XSAVE */
#define CONFIG_FXSAVE  1  /* KernelFPUFXSave=ON */
#define CONFIG_KERNEL_X86_FPU  FXSAVE
#define CONFIG_XSAVE_FEATURE_SET  0
#define CONFIG_XSAVE_SIZE  512
/* disabled: CONFIG_FSGSBASE_INST */
#define CONFIG_FSGSBASE_MSR  1  /* KernelFSGSBaseMSR=ON */
#define CONFIG_KERNEL_FSGS_BASE  msr
/* disabled: CONFIG_MULTIBOOT_GRAPHICS_MODE_NONE */
/* disabled: CONFIG_MULTIBOOT_GRAPHICS_MODE_TEXT */
/* disabled: CONFIG_MULTIBOOT_GRAPHICS_MODE_LINEAR */
#define CONFIG_KERNEL_MUTLTIBOOT_GFX_MODE  none
#define CONFIG_MULTIBOOT_GRAPHICS_MODE_NONE  1  /* KernelMultibootGFXModeNone=ON */
#define CONFIG_MULTIBOOT1_HEADER  1  /* KernelMultiboot1Header=ON */
#define CONFIG_MULTIBOOT2_HEADER  1  /* KernelMultiboot2Header=ON */
#define CONFIG_KERNEL_SKIM_WINDOW  1  /* KernelSkimWindow=ON */
/* disabled: CONFIG_EXPORT_PMC_USER */
/* disabled: CONFIG_KERNEL_X86_DANGEROUS_MSR */
/* disabled: CONFIG_KERNEL_X86_IBRS_NONE */
/* disabled: CONFIG_KERNEL_X86_IBRS_BASIC */
/* disabled: CONFIG_KERNEL_X86_IBRS_ALL */
#define CONFIG_KERNEL_X86_IBRS  ibrs_none
#define CONFIG_KERNEL_X86_IBRS_NONE  1  /* KernelX86IBRSnone=ON */
/* disabled: CONFIG_KERNEL_X86_IBPB_ON_CONTEXT_SWITCH */
/* disabled: CONFIG_KERNEL_X86_RSB_ON_CONTEXT_SWITCH */
#define CONFIG_HAVE_FPU  1  /* KernelHaveFPU=ON */
#define CONFIG_PADDR_USER_DEVICE_TOP  140737488355328
#define CONFIG_ROOT_CNODE_SIZE_BITS  16
#define CONFIG_TIMER_TICK_MS  2
#define CONFIG_TIME_SLICE  5
#define CONFIG_RETYPE_FAN_OUT_LIMIT  256
#define CONFIG_MAX_NUM_WORK_UNITS_PER_PREEMPTION  100
#define CONFIG_RESET_CHUNK_BITS  8
#define CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS  230
#define CONFIG_FASTPATH  1  /* KernelFastpath=ON */
#define CONFIG_NUM_DOMAINS  1
#define CONFIG_NUM_PRIORITIES  256
#define CONFIG_MAX_NUM_NODES  1
/* disabled: CONFIG_ENABLE_SMP_SUPPORT */
#define CONFIG_KERNEL_STACK_BITS  12
#define CONFIG_FPU_MAX_RESTORES_SINCE_SWITCH  64
/* disabled: CONFIG_VERIFICATION_BUILD */
/* disabled: CONFIG_BINARY_VERIFICATION_BUILD */
#define CONFIG_DEBUG_BUILD  1  /* KernelDebugBuild=ON */
/* disabled: CONFIG_HARDWARE_DEBUG_API */
#define CONFIG_PRINTING  1  /* KernelPrinting=ON */
/* disabled: CONFIG_KERNEL_INVOCATION_REPORT_ERROR_IPC */
/* disabled: CONFIG_NO_BENCHMARKS */
/* disabled: CONFIG_BENCHMARK_GENERIC */
/* disabled: CONFIG_BENCHMARK_TRACK_KERNEL_ENTRIES */
/* disabled: CONFIG_BENCHMARK_TRACEPOINTS */
/* disabled: CONFIG_BENCHMARK_TRACK_UTILISATION */
#define CONFIG_KERNEL_BENCHMARK  none
#define CONFIG_NO_BENCHMARKS  1  /* KernelBenchmarksNone=ON */
/* disabled: CONFIG_ENABLE_BENCHMARKS */
/* disabled: CONFIG_KERNEL_LOG_BUFFER */
#define CONFIG_MAX_NUM_TRACE_POINTS  0
#define CONFIG_IRQ_REPORTING  1  /* KernelIRQReporting=ON */
#define CONFIG_COLOUR_PRINTING  1  /* KernelColourPrinting=ON */
#define CONFIG_USER_STACK_TRACE_LENGTH  16
/* disabled: CONFIG_KERNEL_OPT_LEVEL_O2 */
/* disabled: CONFIG_KERNEL_OPT_LEVEL_OS */
/* disabled: CONFIG_KERNEL_OPT_LEVEL_O0 */
/* disabled: CONFIG_KERNEL_OPT_LEVEL_O1 */
/* disabled: CONFIG_KERNEL_OPT_LEVEL_O3 */
#define CONFIG_KERNEL_OPT_LEVEL  -O2
#define CONFIG_KERNEL_OPT_LEVEL_O2  1  /* KernelOptimisationO2=ON */
#define CONFIG_KERNEL_OPTIMISATION_CLONE_FUNCTIONS  1  /* KernelOptimisationCloneFunctions=ON */
/* disabled: CONFIG_KERNEL_FWHOLE_PROGRAM */
/* disabled: CONFIG_DANGEROUS_CODE_INJECTION */
/* disabled: CONFIG_DEBUG_DISABLE_PREFETCHERS */
#define CONFIG_SET_TLS_BASE_SELF  1  /* KernelSetTLSBaseSelf=ON */
/* disabled: CONFIG_CLZ_32 */
/* disabled: CONFIG_CLZ_64 */
/* disabled: CONFIG_CTZ_32 */
/* disabled: CONFIG_CTZ_64 */
/* disabled: CONFIG_CLZ_NO_BUILTIN */
/* disabled: CONFIG_CTZ_NO_BUILTIN */